### ISSUE TITLE
Suggestion : Make SKState descend from ScriptableObject?

### ISSUE THREAD

**Issue by darthbator** [prime31/StateKit#11]
Just wondering is there a reason that the base SKState class does not descend from scriptable object? I tend to make this change anytime I implement this repo (so that I can serialize and drag and drop states inside unity). Has this ever been considered? I just wanted to bring it up somewhere before sending a pull request for it.

**Comment by prime31** [comment]
I personally always prefer to use the highest class up the chain (object in this case). ScriptableObject is a much heavier beast. If you prefer ScriptableObjects it should be as simple as just adding them as a base class just one time when you import StateKit into your project and you're all set.

**Comment by darthbator** [comment]
Cool deal! Just wanted to know if it's something you had thought about. Thanks!
