### ISSUE TITLE
On unity 4.6.5, on import i face this error

### ISSUE THREAD

**Issue by pankajchha** [prime31/StateKit#6]
Assets/StateKit/SKMecanimStateMachine.cs(60,85): error CS1061: Type `UnityEngine.AnimatorStateInfo' does not contain a definition for `fullPathHash' and no extension method `fullPathHash' of type `UnityEngine.AnimatorStateInfo' could be found (are you missing a using directive or an assembly reference?)

**Comment by prime31** [comment]
fullPathHash is Unity 5 only. All of the *Kits have moved to Unity 5 (Unity 4 only has 1 more month to live so it was time to move on).
