### ISSUE TITLE
State change while in State_Exit() calls the same State_Exit()

### ISSUE THREAD

**Issue by tosiabunio** [prime31/StateKit#8]
Should this work that way? We are still exiting the state, but when destination changes it should only affect which State_Enter() is called if we change state during exit and State_Exit() is finished.

**Comment by prime31** [comment]
changing states while in an exit state is a bit odd. The code definitely does not expect that to happen. State changes are expected to be happening in the tick method. Whatever state is currently active will always have exit called when a state changes regardless of when it changes.
